export type IconName =
  | 'account-circle'
  | 'add-circle'
  | 'arrow-back'
  | 'add-photo'
  | 'cancel'
  | 'close'
  | 'forum'
  | 'favorite'
  | 'edit'
  | 'home'
  | 'sms'
  | 'notifications'
  | 'search'
  | 'send'
  | 'more-vert';
